---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demoapp
  name: demoapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    app: demoapp